# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  ImGui_config = debug_x64
  Stb_image_config = debug_x64
  GLFW_config = debug_x64
  SimdJson_config = debug_x64
  Hydrogen_config = debug_x64
  Xenon_config = debug_x64
  SandBox_config = debug_x64

else ifeq ($(config),release_x64)
  ImGui_config = release_x64
  Stb_image_config = release_x64
  GLFW_config = release_x64
  SimdJson_config = release_x64
  Hydrogen_config = release_x64
  Xenon_config = release_x64
  SandBox_config = release_x64

else ifeq ($(config),distrib_x64)
  ImGui_config = distrib_x64
  Stb_image_config = distrib_x64
  GLFW_config = distrib_x64
  SimdJson_config = distrib_x64
  Hydrogen_config = distrib_x64
  Xenon_config = distrib_x64
  SandBox_config = distrib_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ImGui Stb_image GLFW SimdJson Hydrogen Xenon SandBox

.PHONY: all clean help $(PROJECTS) Core Dependencies Misc

all: $(PROJECTS)

Core: Hydrogen Xenon

Dependencies: GLFW ImGui SimdJson Stb_image

Misc: SandBox

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/imgui -f Makefile config=$(ImGui_config)
endif

Stb_image:
ifneq (,$(Stb_image_config))
	@echo "==== Building Stb_image ($(Stb_image_config)) ===="
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/stb_image -f Makefile config=$(Stb_image_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/glfw -f Makefile config=$(GLFW_config)
endif

SimdJson:
ifneq (,$(SimdJson_config))
	@echo "==== Building SimdJson ($(SimdJson_config)) ===="
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/SimdJson -f Makefile config=$(SimdJson_config)
endif

Hydrogen: GLFW ImGui Stb_image SimdJson Xenon
ifneq (,$(Hydrogen_config))
	@echo "==== Building Hydrogen ($(Hydrogen_config)) ===="
	@${MAKE} --no-print-directory -C Hydrogen/Engine -f Makefile config=$(Hydrogen_config)
endif

Xenon: SimdJson
ifneq (,$(Xenon_config))
	@echo "==== Building Xenon ($(Xenon_config)) ===="
	@${MAKE} --no-print-directory -C Hydrogen/Xenon -f Makefile config=$(Xenon_config)
endif

SandBox: Hydrogen
ifneq (,$(SandBox_config))
	@echo "==== Building SandBox ($(SandBox_config)) ===="
	@${MAKE} --no-print-directory -C SandBox -f Makefile config=$(SandBox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/stb_image -f Makefile clean
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Hydrogen/3rdParty/SimdJson -f Makefile clean
	@${MAKE} --no-print-directory -C Hydrogen/Engine -f Makefile clean
	@${MAKE} --no-print-directory -C Hydrogen/Xenon -f Makefile clean
	@${MAKE} --no-print-directory -C SandBox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo "  distrib_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   Stb_image"
	@echo "   GLFW"
	@echo "   SimdJson"
	@echo "   Hydrogen"
	@echo "   Xenon"
	@echo "   SandBox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"