#pragma once
#include <vulkan/vulkan.h>
#include <vulkan/vulkan_core.h>

namespace Hydrogen
{


    //Redefinition of Vulkan's Pipeline Related flags
    enum PrimitiveTopology
    {
        HYD_PRIMITIVE_TOPOLOGY_POINT_LIST                    = VK_PRIMITIVE_TOPOLOGY_POINT_LIST,
        HYD_PRIMITIVE_TOPOLOGY_LINE_LIST                     = VK_PRIMITIVE_TOPOLOGY_LINE_LIST,
        HYD_PRIMITIVE_TOPOLOGY_LINE_STRIP                    = VK_PRIMITIVE_TOPOLOGY_LINE_STRIP,
        HYD_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST                 = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        HYD_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP                = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP,
        HYD_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN                  = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN,
        HYD_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY      = VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY,
        HYD_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY     = VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY,
        HYD_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY  = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY,
        HYD_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY,
        HYD_PRIMITIVE_TOPOLOGY_PATCH_LIST                    = VK_PRIMITIVE_TOPOLOGY_PATCH_LIST,
        HYD_PRIMITIVE_TOPOLOGY_MAX_ENUM                      = VK_PRIMITIVE_TOPOLOGY_MAX_ENUM
    };

    enum PolygonMode
    {
        HYD_POLYGON_MODE_FILL               = VK_POLYGON_MODE_FILL,
        HYD_POLYGON_MODE_LINE               = VK_POLYGON_MODE_LINE,
        HYD_POLYGON_MODE_POINT              = VK_POLYGON_MODE_POINT,
        HYD_POLYGON_MODE_FILL_RECTANGLE_NV  = VK_POLYGON_MODE_FILL_RECTANGLE_NV,
        HYD_POLYGON_MODE_MAX_ENUM           = VK_POLYGON_MODE_MAX_ENUM
    };

    enum CullModes
    {
        HYD_CULL_MODE_NONE               = VK_CULL_MODE_NONE,
        HYD_CULL_MODE_FRONT          = VK_CULL_MODE_FRONT_BIT,
        HYD_CULL_MODE_BACK           = VK_CULL_MODE_BACK_BIT,
        HYD_CULL_MODE_FRONT_AND_BACK     = VK_CULL_MODE_FRONT_AND_BACK,
        HYD_CULL_MODE_FLAG_BITS_MAX_ENUM = VK_CULL_MODE_FLAG_BITS_MAX_ENUM
    };

    enum FrontFace
    {
        HYD_FRONT_FACE_COUNTER_CLOCKWISE = VK_FRONT_FACE_COUNTER_CLOCKWISE,
        HYD_FRONT_FACE_CLOCKWISE         = VK_FRONT_FACE_CLOCKWISE,
        HYD_FRONT_FACE_MAX_ENUM          = VK_FRONT_FACE_MAX_ENUM
    };


    enum DynamicState
    {
        HYD_DYNAMIC_STATE_VIEWPORT                    = VK_DYNAMIC_STATE_VIEWPORT,
        HYD_DYNAMIC_STATE_SCISSOR                     = VK_DYNAMIC_STATE_SCISSOR,
        HYD_DYNAMIC_STATE_LINE_WIDTH                  = VK_DYNAMIC_STATE_LINE_WIDTH,
        HYD_DYNAMIC_STATE_DEPTH_BIAS                  = VK_DYNAMIC_STATE_DEPTH_BIAS,
        HYD_DYNAMIC_STATE_BLEND_CONSTANTS             = VK_DYNAMIC_STATE_BLEND_CONSTANTS,
        HYD_DYNAMIC_STATE_DEPTH_BOUNDS                = VK_DYNAMIC_STATE_DEPTH_BOUNDS,
        HYD_DYNAMIC_STATE_STENCIL_COMPARE_MASK        = VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK,
        HYD_DYNAMIC_STATE_STENCIL_WRITE_MASK          = VK_DYNAMIC_STATE_STENCIL_WRITE_MASK,
        HYD_DYNAMIC_STATE_STENCIL_REFERENCE           = VK_DYNAMIC_STATE_STENCIL_REFERENCE,
        HYD_DYNAMIC_STATE_CULL_MODE                   = VK_DYNAMIC_STATE_CULL_MODE,
        HYD_DYNAMIC_STATE_FRONT_FACE                  = VK_DYNAMIC_STATE_FRONT_FACE,
        HYD_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY          = VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY,
        HYD_DYNAMIC_STATE_VIEWPORT_WITH_COUNT         = VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT,
        HYD_DYNAMIC_STATE_SCISSOR_WITH_COUNT          = VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT,
        HYD_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE = VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE,
        HYD_DYNAMIC_STATE_DEPTH_TEST_ENABLE           = VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE,
        HYD_DYNAMIC_STATE_DEPTH_WRITE_ENABLE          = VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE,
        HYD_DYNAMIC_STATE_DEPTH_COMPARE_OP            = VK_DYNAMIC_STATE_DEPTH_COMPARE_OP,
        HYD_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE    = VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE,
        HYD_DYNAMIC_STATE_STENCIL_TEST_ENABLE         = VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE,
        HYD_DYNAMIC_STATE_STENCIL_OP                  = VK_DYNAMIC_STATE_STENCIL_OP,
        HYD_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE   = VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE,
        HYD_DYNAMIC_STATE_DEPTH_BIAS_ENABLE           = VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE,
        HYD_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE    = VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE,
        HYD_DYNAMIC_STATE_LINE_STIPPLE                = VK_DYNAMIC_STATE_LINE_STIPPLE,

    };


    enum LogicOperations
    {
        HYD_LOGIC_OP_CLEAR         = VK_LOGIC_OP_CLEAR,
        HYD_LOGIC_OP_AND           = VK_LOGIC_OP_AND,
        HYD_LOGIC_OP_AND_REVERSE   = VK_LOGIC_OP_AND_REVERSE,
        HYD_LOGIC_OP_COPY          = VK_LOGIC_OP_COPY,
        HYD_LOGIC_OP_AND_INVERTED  = VK_LOGIC_OP_AND_INVERTED,
        HYD_LOGIC_OP_NO_OP         = VK_LOGIC_OP_NO_OP,
        HYD_LOGIC_OP_XOR           = VK_LOGIC_OP_XOR,
        HYD_LOGIC_OP_OR            = VK_LOGIC_OP_OR,
        HYD_LOGIC_OP_NOR           = VK_LOGIC_OP_NOR,
        HYD_LOGIC_OP_EQUIVALENT    = VK_LOGIC_OP_EQUIVALENT,
        HYD_LOGIC_OP_INVERT        = VK_LOGIC_OP_INVERT,
        HYD_LOGIC_OP_OR_REVERSE    = VK_LOGIC_OP_OR_REVERSE,
        HYD_LOGIC_OP_COPY_INVERTED = VK_LOGIC_OP_COPY_INVERTED,
        HYD_LOGIC_OP_OR_INVERTED   = VK_LOGIC_OP_OR_INVERTED,
        HYD_LOGIC_OP_NAND          = VK_LOGIC_OP_NAND,
        HYD_LOGIC_OP_SET           = VK_LOGIC_OP_SET,
        HYD_LOGIC_OP_MAX_ENUM      = VK_LOGIC_OP_MAX_ENUM 
    };


    enum CompareOperation {
        HYD_COMPARE_OP_NEVER            = VK_COMPARE_OP_NEVER,
        HYD_COMPARE_OP_LESS             = VK_COMPARE_OP_LESS,
        HYD_COMPARE_OP_EQUAL            = VK_COMPARE_OP_EQUAL,
        HYD_COMPARE_OP_LESS_OR_EQUAL    = VK_COMPARE_OP_LESS_OR_EQUAL,
        HYD_COMPARE_OP_GREATER          = VK_COMPARE_OP_GREATER,
        HYD_COMPARE_OP_NOT_EQUAL        = VK_COMPARE_OP_NOT_EQUAL,
        HYD_COMPARE_OP_GREATER_OR_EQUAL = VK_COMPARE_OP_GREATER_OR_EQUAL,
        HYD_COMPARE_OP_ALWAYS           = VK_COMPARE_OP_ALWAYS,
        HYD_COMPARE_OP_MAX_ENUM         = VK_COMPARE_OP_MAX_ENUM 
    };

    enum ImageFormat
    {
        HYD_FORMAT_UNDEFINED                  = VK_FORMAT_UNDEFINED,
        HYD_FORMAT_R4G4_UNORM_PACK8           = VK_FORMAT_R4G4_UNORM_PACK8,
        HYD_FORMAT_R4G4B4A4_UNORM_PACK16      = VK_FORMAT_R4G4B4A4_UNORM_PACK16 ,
        HYD_FORMAT_B4G4R4A4_UNORM_PACK16      = VK_FORMAT_B4G4R4A4_UNORM_PACK16 ,
        HYD_FORMAT_R5G6B5_UNORM_PACK16        = VK_FORMAT_R5G6B5_UNORM_PACK16 ,
        HYD_FORMAT_B5G6R5_UNORM_PACK16        = VK_FORMAT_B5G6R5_UNORM_PACK16 ,
        HYD_FORMAT_R5G5B5A1_UNORM_PACK16      = VK_FORMAT_R5G5B5A1_UNORM_PACK16,
        HYD_FORMAT_B5G5R5A1_UNORM_PACK16      = VK_FORMAT_B5G5R5A1_UNORM_PACK16,
        HYD_FORMAT_A1R5G5B5_UNORM_PACK16      = VK_FORMAT_A1R5G5B5_UNORM_PACK16,
        HYD_FORMAT_R8_UNORM                   = VK_FORMAT_R8_UNORM ,
        HYD_FORMAT_R8_SNORM                   = VK_FORMAT_R8_SNORM ,
        HYD_FORMAT_R8_USCALED                 = VK_FORMAT_R8_USCALED ,
        HYD_FORMAT_R8_SSCALED                 = VK_FORMAT_R8_SSCALED ,
        HYD_FORMAT_R8_UINT                    = VK_FORMAT_R8_UINT ,
        HYD_FORMAT_R8_SINT                    = VK_FORMAT_R8_SINT ,
        HYD_FORMAT_R8_SRGB                    = VK_FORMAT_R8_SRGB ,
        HYD_FORMAT_R8G8_UNORM                 = VK_FORMAT_R8G8_UNORM,
        HYD_FORMAT_R8G8_SNORM                 = VK_FORMAT_R8G8_SNORM,
        HYD_FORMAT_R8G8_USCALED               = VK_FORMAT_R8G8_USCALED,
        HYD_FORMAT_R8G8_SSCALED               = VK_FORMAT_R8G8_SSCALED,
        HYD_FORMAT_R8G8_UINT                  = VK_FORMAT_R8G8_UINT,
        HYD_FORMAT_R8G8_SINT                  = VK_FORMAT_R8G8_SINT,
        HYD_FORMAT_R8G8_SRGB                  = VK_FORMAT_R8G8_SRGB,
        HYD_FORMAT_R8G8B8_UNORM               = VK_FORMAT_R8G8B8_UNORM,
        HYD_FORMAT_R8G8B8_SNORM               = VK_FORMAT_R8G8B8_SNORM,
        HYD_FORMAT_R8G8B8_USCALED             = VK_FORMAT_R8G8B8_USCALED,
        HYD_FORMAT_R8G8B8_SSCALED             = VK_FORMAT_R8G8B8_SSCALED,
        HYD_FORMAT_R8G8B8_UINT                = VK_FORMAT_R8G8B8_UINT,
        HYD_FORMAT_R8G8B8_SINT                = VK_FORMAT_R8G8B8_SINT,
        HYD_FORMAT_R8G8B8_SRGB                = VK_FORMAT_R8G8B8_SRGB,
        HYD_FORMAT_B8G8R8_UNORM               = VK_FORMAT_B8G8R8_UNORM,
        HYD_FORMAT_B8G8R8_SNORM               = VK_FORMAT_B8G8R8_SNORM,
        HYD_FORMAT_B8G8R8_USCALED             = VK_FORMAT_B8G8R8_USCALED,
        HYD_FORMAT_B8G8R8_SSCALED             = VK_FORMAT_B8G8R8_SSCALED,
        HYD_FORMAT_B8G8R8_UINT                = VK_FORMAT_B8G8R8_UINT,
        HYD_FORMAT_B8G8R8_SINT                = VK_FORMAT_B8G8R8_SINT,
        HYD_FORMAT_B8G8R8_SRGB                = VK_FORMAT_B8G8R8_SRGB,
        HYD_FORMAT_R8G8B8A8_UNORM             = VK_FORMAT_R8G8B8A8_UNORM,
        HYD_FORMAT_R8G8B8A8_SNORM             = VK_FORMAT_R8G8B8A8_SNORM,
        HYD_FORMAT_R8G8B8A8_USCALED           = VK_FORMAT_R8G8B8A8_USCALED,
        HYD_FORMAT_R8G8B8A8_SSCALED           = VK_FORMAT_R8G8B8A8_SSCALED,
        HYD_FORMAT_R8G8B8A8_UINT              = VK_FORMAT_R8G8B8A8_UINT,
        HYD_FORMAT_R8G8B8A8_SINT              = VK_FORMAT_R8G8B8A8_SINT,
        HYD_FORMAT_R8G8B8A8_SRGB              = VK_FORMAT_R8G8B8A8_SRGB,
        HYD_FORMAT_B8G8R8A8_UNORM             = VK_FORMAT_B8G8R8A8_UNORM,
        HYD_FORMAT_B8G8R8A8_SNORM             = VK_FORMAT_B8G8R8A8_SNORM,
        HYD_FORMAT_B8G8R8A8_USCALED           = VK_FORMAT_B8G8R8A8_USCALED,
        HYD_FORMAT_B8G8R8A8_SSCALED           = VK_FORMAT_B8G8R8A8_SSCALED,
        HYD_FORMAT_B8G8R8A8_UINT              = VK_FORMAT_B8G8R8A8_UINT,
        HYD_FORMAT_B8G8R8A8_SINT              = VK_FORMAT_B8G8R8A8_SINT,
        HYD_FORMAT_B8G8R8A8_SRGB              = VK_FORMAT_B8G8R8A8_SRGB,
        HYD_FORMAT_A8B8G8R8_UNORM_PACK32      = VK_FORMAT_A8B8G8R8_UNORM_PACK32,
        HYD_FORMAT_A8B8G8R8_SNORM_PACK32      = VK_FORMAT_A8B8G8R8_SNORM_PACK32,
        HYD_FORMAT_A8B8G8R8_USCALED_PACK32    = VK_FORMAT_A8B8G8R8_USCALED_PACK32,
        HYD_FORMAT_A8B8G8R8_SSCALED_PACK32    = VK_FORMAT_A8B8G8R8_SSCALED_PACK32,
        HYD_FORMAT_A8B8G8R8_UINT_PACK32       = VK_FORMAT_A8B8G8R8_UINT_PACK32,
        HYD_FORMAT_A8B8G8R8_SINT_PACK32       = VK_FORMAT_A8B8G8R8_SINT_PACK32,
        HYD_FORMAT_A8B8G8R8_SRGB_PACK32       = VK_FORMAT_A8B8G8R8_SRGB_PACK32,
        HYD_FORMAT_A2R10G10B10_UNORM_PACK32   = VK_FORMAT_A2R10G10B10_UNORM_PACK32,
        HYD_FORMAT_A2R10G10B10_SNORM_PACK32   = VK_FORMAT_A2R10G10B10_SNORM_PACK32,
        HYD_FORMAT_A2R10G10B10_USCALED_PACK32 = VK_FORMAT_A2R10G10B10_USCALED_PACK32,
        HYD_FORMAT_A2R10G10B10_SSCALED_PACK32 = VK_FORMAT_A2R10G10B10_SSCALED_PACK32,
        HYD_FORMAT_A2R10G10B10_UINT_PACK32    = VK_FORMAT_A2R10G10B10_UINT_PACK32,
        HYD_FORMAT_A2R10G10B10_SINT_PACK32    = VK_FORMAT_A2R10G10B10_SINT_PACK32,
        HYD_FORMAT_A2B10G10R10_UNORM_PACK32   = VK_FORMAT_A2B10G10R10_UNORM_PACK32,
        HYD_FORMAT_A2B10G10R10_SNORM_PACK32   = VK_FORMAT_A2B10G10R10_SNORM_PACK32,
        HYD_FORMAT_A2B10G10R10_USCALED_PACK32 = VK_FORMAT_A2B10G10R10_USCALED_PACK32,
        HYD_FORMAT_A2B10G10R10_SSCALED_PACK32 = VK_FORMAT_A2B10G10R10_SSCALED_PACK32,
        HYD_FORMAT_A2B10G10R10_UINT_PACK32    = VK_FORMAT_A2B10G10R10_UINT_PACK32,
        HYD_FORMAT_A2B10G10R10_SINT_PACK32    = VK_FORMAT_A2B10G10R10_SINT_PACK32,
        HYD_FORMAT_R16_UNORM                  = VK_FORMAT_R16_UNORM,
        HYD_FORMAT_R16_SNORM                  = VK_FORMAT_R16_SNORM,
        HYD_FORMAT_R16_USCALED                = VK_FORMAT_R16_USCALED,
        HYD_FORMAT_R16_SSCALED                = VK_FORMAT_R16_SSCALED,
        HYD_FORMAT_R16_UINT                   = VK_FORMAT_R16_UINT,
        HYD_FORMAT_R16_SINT                   = VK_FORMAT_R16_SINT,
        HYD_FORMAT_R16_SFLOAT                 = VK_FORMAT_R16_SFLOAT,
        HYD_FORMAT_R16G16_UNORM               = VK_FORMAT_R16G16_UNORM,
        HYD_FORMAT_R16G16_SNORM               = VK_FORMAT_R16G16_SNORM,
        HYD_FORMAT_R16G16_USCALED             = VK_FORMAT_R16G16_USCALED,
        HYD_FORMAT_R16G16_SSCALED             = VK_FORMAT_R16G16_SSCALED,
        HYD_FORMAT_R16G16_UINT                = VK_FORMAT_R16G16_UINT,
        HYD_FORMAT_R16G16_SINT                = VK_FORMAT_R16G16_SINT,
        HYD_FORMAT_R16G16_SFLOAT              = VK_FORMAT_R16G16_SFLOAT,
        HYD_FORMAT_R16G16B16_UNORM            = VK_FORMAT_R16G16B16_UNORM,
        HYD_FORMAT_R16G16B16_SNORM            = VK_FORMAT_R16G16B16_SNORM,
        HYD_FORMAT_R16G16B16_USCALED          = VK_FORMAT_R16G16B16_USCALED,
        HYD_FORMAT_R16G16B16_SSCALED          = VK_FORMAT_R16G16B16_SSCALED,
        HYD_FORMAT_R16G16B16_UINT             = VK_FORMAT_R16G16B16_UINT,
        HYD_FORMAT_R16G16B16_SINT             = VK_FORMAT_R16G16B16_SINT,
        HYD_FORMAT_R16G16B16_SFLOAT           = VK_FORMAT_R16G16B16_SFLOAT,
        HYD_FORMAT_R16G16B16A16_UNORM         = VK_FORMAT_R16G16B16A16_UNORM,
        HYD_FORMAT_R16G16B16A16_SNORM         = VK_FORMAT_R16G16B16A16_SNORM,
        HYD_FORMAT_R16G16B16A16_USCALED       = VK_FORMAT_R16G16B16A16_USCALED,
        HYD_FORMAT_R16G16B16A16_SSCALED       = VK_FORMAT_R16G16B16A16_SSCALED,
        HYD_FORMAT_R16G16B16A16_UINT          = VK_FORMAT_R16G16B16A16_UINT   ,
        HYD_FORMAT_R16G16B16A16_SINT          = VK_FORMAT_R16G16B16A16_SINT   ,
        HYD_FORMAT_R16G16B16A16_SFLOAT        = VK_FORMAT_R16G16B16A16_SFLOAT ,
        HYD_FORMAT_R32_UINT                   = VK_FORMAT_R32_UINT            ,
        HYD_FORMAT_R32_SINT                   = VK_FORMAT_R32_SINT            ,
        HYD_FORMAT_R32_SFLOAT                 = VK_FORMAT_R32_SFLOAT          ,
        HYD_FORMAT_R32G32_UINT                = VK_FORMAT_R32G32_UINT         ,
        HYD_FORMAT_R32G32_SINT                = VK_FORMAT_R32G32_SINT         ,
        HYD_FORMAT_R32G32_SFLOAT              = VK_FORMAT_R32G32_SFLOAT       ,
        HYD_FORMAT_R32G32B32_UINT             = VK_FORMAT_R32G32B32_UINT      ,
        HYD_FORMAT_R32G32B32_SINT             = VK_FORMAT_R32G32B32_SINT      ,
        HYD_FORMAT_R32G32B32_SFLOAT           = VK_FORMAT_R32G32B32_SFLOAT    ,
        HYD_FORMAT_R32G32B32A32_UINT          = VK_FORMAT_R32G32B32A32_UINT   ,
        HYD_FORMAT_R32G32B32A32_SINT          = VK_FORMAT_R32G32B32A32_SINT   ,
        HYD_FORMAT_R32G32B32A32_SFLOAT        = VK_FORMAT_R32G32B32A32_SFLOAT ,
        HYD_FORMAT_R64_UINT                   = VK_FORMAT_R64_UINT            ,
        HYD_FORMAT_R64_SINT                   = VK_FORMAT_R64_SINT            ,
        HYD_FORMAT_R64_SFLOAT                 = VK_FORMAT_R64_SFLOAT          ,
        HYD_FORMAT_R64G64_UINT                = VK_FORMAT_R64G64_UINT         ,
        HYD_FORMAT_R64G64_SINT                = VK_FORMAT_R64G64_SINT         ,
        HYD_FORMAT_R64G64_SFLOAT              = VK_FORMAT_R64G64_SFLOAT       ,
        HYD_FORMAT_R64G64B64_UINT             = VK_FORMAT_R64G64B64_UINT      ,
        HYD_FORMAT_R64G64B64_SINT             = VK_FORMAT_R64G64B64_SINT      ,
        HYD_FORMAT_R64G64B64_SFLOAT           = VK_FORMAT_R64G64B64_SFLOAT    ,
        HYD_FORMAT_R64G64B64A64_UINT          = VK_FORMAT_R64G64B64A64_UINT   ,
        HYD_FORMAT_R64G64B64A64_SINT          = VK_FORMAT_R64G64B64A64_SINT   ,
        HYD_FORMAT_R64G64B64A64_SFLOAT        = VK_FORMAT_R64G64B64A64_SFLOAT ,
        HYD_FORMAT_B10G11R11_UFLOAT_PACK32    = VK_FORMAT_B10G11R11_UFLOAT_PACK32,
        HYD_FORMAT_E5B9G9R9_UFLOAT_PACK32     = VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 ,
        HYD_FORMAT_D16_UNORM                  = VK_FORMAT_D16_UNORM              ,
        HYD_FORMAT_X8_D24_UNORM_PACK32        = VK_FORMAT_X8_D24_UNORM_PACK32    ,
        HYD_FORMAT_D32_SFLOAT                 = VK_FORMAT_D32_SFLOAT             ,
        HYD_FORMAT_S8_UINT                    = VK_FORMAT_S8_UINT                ,
        HYD_FORMAT_D16_UNORM_S8_UINT          = VK_FORMAT_D16_UNORM_S8_UINT      ,
        HYD_FORMAT_D24_UNORM_S8_UINT          = VK_FORMAT_D24_UNORM_S8_UINT      ,
        HYD_FORMAT_D32_SFLOAT_S8_UINT         = VK_FORMAT_D32_SFLOAT_S8_UINT     
    };


    enum ImageViewType
    {
        HYD_IMAGE_VIEW_TYPE_1D         = VK_IMAGE_VIEW_TYPE_1D,
        HYD_IMAGE_VIEW_TYPE_2D         = VK_IMAGE_VIEW_TYPE_2D,
        HYD_IMAGE_VIEW_TYPE_3D         = VK_IMAGE_VIEW_TYPE_3D,
        HYD_IMAGE_VIEW_TYPE_CUBE       = VK_IMAGE_VIEW_TYPE_CUBE,
        HYD_IMAGE_VIEW_TYPE_1D_ARRAY   = VK_IMAGE_VIEW_TYPE_1D_ARRAY,
        HYD_IMAGE_VIEW_TYPE_2D_ARRAY   = VK_IMAGE_VIEW_TYPE_2D_ARRAY,
        HYD_IMAGE_VIEW_TYPE_CUBE_ARRAY = VK_IMAGE_VIEW_TYPE_CUBE_ARRAY,
        HYD_IMAGE_VIEW_TYPE_MAX_ENUM   = VK_IMAGE_VIEW_TYPE_MAX_ENUM
    };

    enum ComponentSwizzle
    {
        HYD_COMPONENT_SWIZZLE_IDENTITY = VK_COMPONENT_SWIZZLE_IDENTITY,
        HYD_COMPONENT_SWIZZLE_ZERO     = VK_COMPONENT_SWIZZLE_ZERO,
        HYD_COMPONENT_SWIZZLE_ONE      = VK_COMPONENT_SWIZZLE_ONE,
        HYD_COMPONENT_SWIZZLE_R        = VK_COMPONENT_SWIZZLE_R,
        HYD_COMPONENT_SWIZZLE_G        = VK_COMPONENT_SWIZZLE_G,
        HYD_COMPONENT_SWIZZLE_B        = VK_COMPONENT_SWIZZLE_B,
        HYD_COMPONENT_SWIZZLE_A        = VK_COMPONENT_SWIZZLE_A,
        HYD_COMPONENT_SWIZZLE_MAX_ENUM = VK_COMPONENT_SWIZZLE_MAX_ENUM
    };


    enum LoadOperation
    {
        HYD_ATTACHMENT_LOAD_OP_LOAD      = VK_ATTACHMENT_LOAD_OP_LOAD,
        HYD_ATTACHMENT_LOAD_OP_CLEAR     = VK_ATTACHMENT_LOAD_OP_CLEAR,
        HYD_ATTACHMENT_LOAD_OP_DONT_CARE = VK_ATTACHMENT_LOAD_OP_DONT_CARE
    };

    enum StoreOperation
    {
        HYD_ATTACHMENT_STORE_OP_STORE      = VK_ATTACHMENT_STORE_OP_STORE,
        HYD_ATTACHMENT_STORE_OP_DONT_CARE  = VK_ATTACHMENT_STORE_OP_DONT_CARE
    };


    enum ImageSampleCount
    {
        HYD_SAMPLE_COUNT_1_BIT   = VK_SAMPLE_COUNT_1_BIT,
        HYD_SAMPLE_COUNT_2_BIT   = VK_SAMPLE_COUNT_2_BIT,
        HYD_SAMPLE_COUNT_4_BIT   = VK_SAMPLE_COUNT_4_BIT,
        HYD_SAMPLE_COUNT_8_BIT   = VK_SAMPLE_COUNT_8_BIT,
        HYD_SAMPLE_COUNT_16_BIT  = VK_SAMPLE_COUNT_16_BIT,
        HYD_SAMPLE_COUNT_32_BIT  = VK_SAMPLE_COUNT_32_BIT,
        HYD_SAMPLE_COUNT_64_BIT  = VK_SAMPLE_COUNT_64_BIT
    };


    enum ImageLayout
    {
        HYD_IMAGE_LAYOUT_UNDEFINED                                  = VK_IMAGE_LAYOUT_UNDEFINED,
        HYD_IMAGE_LAYOUT_GENERAL                                    = VK_IMAGE_LAYOUT_GENERAL,
        HYD_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL                   = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        HYD_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL           = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
        HYD_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL            = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
        HYD_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL                   = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
        HYD_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL                       = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        HYD_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL                       = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        HYD_IMAGE_LAYOUT_PREINITIALIZED                             = VK_IMAGE_LAYOUT_PREINITIALIZED,
        HYD_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
        HYD_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
        HYD_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL                   = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
        HYD_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL                    = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
        HYD_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL                 = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
        HYD_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL                  = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
        HYD_IMAGE_LAYOUT_READ_ONLY_OPTIMAL                          = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
        HYD_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL                         = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
        HYD_IMAGE_LAYOUT_RENDERING_LOCAL_READ                       = VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ,
        HYD_IMAGE_LAYOUT_PRESENT_SRC_KHR                            = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR
    };


    enum ImageUsage : uint32_t
    {
        HYD_IMAGE_USAGE_TRANSFER_SRC_BIT             = VK_IMAGE_USAGE_TRANSFER_SRC_BIT,
        HYD_IMAGE_USAGE_TRANSFER_DST_BIT             = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
        HYD_IMAGE_USAGE_SAMPLED_BIT                  = VK_IMAGE_USAGE_SAMPLED_BIT,
        HYD_IMAGE_USAGE_STORAGE_BIT                  = VK_IMAGE_USAGE_STORAGE_BIT,
        HYD_IMAGE_USAGE_COLOR_ATTACHMENT_BIT         = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
        HYD_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
        HYD_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT     = VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT,
        HYD_IMAGE_USAGE_INPUT_ATTACHMENT_BIT         = VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT,
        HYD_IMAGE_USAGE_HOST_TRANSFER_BIT            = VK_IMAGE_USAGE_HOST_TRANSFER_BIT
    };


    enum ImageType
    {
        HYD_IMAGE_TYPE_1D       = VK_IMAGE_TYPE_1D,
        HYD_IMAGE_TYPE_2D       = VK_IMAGE_TYPE_2D,
        HYD_IMAGE_TYPE_3D       = VK_IMAGE_TYPE_3D,
        HYD_IMAGE_TYPE_MAX_ENUM = VK_IMAGE_TYPE_MAX_ENUM
    };


    enum PipelineStageFlags
    {
        HYD_PIPELINE_STAGE_TOP_OF_PIPE                    = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
        HYD_PIPELINE_STAGE_DRAW_INDIRECT                  = VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
        HYD_PIPELINE_STAGE_VERTEX_INPUT                   = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
        HYD_PIPELINE_STAGE_VERTEX_SHADER                  = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,
        HYD_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER    = VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT,
        HYD_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER = VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT,
        HYD_PIPELINE_STAGE_GEOMETRY_SHADER                = VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT,
        HYD_PIPELINE_STAGE_FRAGMENT_SHADER                = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
        HYD_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS           = VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
        HYD_PIPELINE_STAGE_LATE_FRAGMENT_TESTS            = VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
        HYD_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT        = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
        HYD_PIPELINE_STAGE_COMPUTE_SHADER                 = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        HYD_PIPELINE_STAGE_TRANSFER                       = VK_PIPELINE_STAGE_TRANSFER_BIT,
        HYD_PIPELINE_STAGE_BOTTOM_OF_PIPE                 = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
        HYD_PIPELINE_STAGE_HOST                           = VK_PIPELINE_STAGE_HOST_BIT,
        HYD_PIPELINE_STAGE_ALL_GRAPHICS                   = VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT,
        HYD_PIPELINE_STAGE_ALL_COMMANDS                   = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
        HYD_PIPELINE_STAGE_NONE                           = VK_PIPELINE_STAGE_NONE
    };


    enum AccessFlags
    {
        HYD_ACCESS_INDIRECT_COMMAND_READ          = VK_ACCESS_INDIRECT_COMMAND_READ_BIT,
        HYD_ACCESS_INDEX_READ                     = VK_ACCESS_INDEX_READ_BIT,
        HYD_ACCESS_VERTEX_ATTRIBUTE_READ          = VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT,
        HYD_ACCESS_UNIFORM_READ                   = VK_ACCESS_UNIFORM_READ_BIT,
        HYD_ACCESS_INPUT_ATTACHMENT_READ          = VK_ACCESS_INPUT_ATTACHMENT_READ_BIT,
        HYD_ACCESS_SHADER_READ                    = VK_ACCESS_SHADER_READ_BIT,
        HYD_ACCESS_SHADER_WRITE                   = VK_ACCESS_SHADER_WRITE_BIT,
        HYD_ACCESS_COLOR_ATTACHMENT_READ          = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT,
        HYD_ACCESS_COLOR_ATTACHMENT_WRITE         = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
        HYD_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ  = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT,
        HYD_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
        HYD_ACCESS_TRANSFER_READ                  = VK_ACCESS_TRANSFER_READ_BIT,
        HYD_ACCESS_TRANSFER_WRITE                 = VK_ACCESS_TRANSFER_WRITE_BIT,
        HYD_ACCESS_HOST_READ                      = VK_ACCESS_HOST_READ_BIT,
        HYD_ACCESS_HOST_WRITE                     = VK_ACCESS_HOST_WRITE_BIT,
        HYD_ACCESS_MEMORY_READ                    = VK_ACCESS_MEMORY_READ_BIT,
        HYD_ACCESS_MEMORY_WRITE                   = VK_ACCESS_MEMORY_WRITE_BIT,
        HYD_ACCESS_NONE                           = VK_ACCESS_NONE
    };

    enum ShaderStages
    {
        HYD_SHADER_STAGE_VERTEX_BIT                  = VK_SHADER_STAGE_VERTEX_BIT,
        HYD_SHADER_STAGE_TESSELLATION_CONTROL_BIT    = VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT,
        HYD_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT,
        HYD_SHADER_STAGE_GEOMETRY_BIT                = VK_SHADER_STAGE_GEOMETRY_BIT,
        HYD_SHADER_STAGE_FRAGMENT_BIT                = VK_SHADER_STAGE_FRAGMENT_BIT,
        HYD_SHADER_STAGE_COMPUTE_BIT                 = VK_SHADER_STAGE_COMPUTE_BIT,
        HYD_SHADER_STAGE_ALL_GRAPHICS                = VK_SHADER_STAGE_ALL_GRAPHICS,
        HYD_SHADER_STAGE_ALL                         = VK_SHADER_STAGE_ALL    
    };

    enum UniformType
    {
        HYD_DESCRIPTOR_TYPE_SAMPLER                = VK_DESCRIPTOR_TYPE_SAMPLER,
        HYD_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
        HYD_DESCRIPTOR_TYPE_SAMPLED_IMAGE          = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
        HYD_DESCRIPTOR_TYPE_STORAGE_IMAGE          = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
        HYD_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER   = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
        HYD_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER   = VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
        HYD_DESCRIPTOR_TYPE_UNIFORM_BUFFER         = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        HYD_DESCRIPTOR_TYPE_STORAGE_BUFFER         = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
        HYD_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
        HYD_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
        HYD_DESCRIPTOR_TYPE_INPUT_ATTACHMENT       = VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,
        HYD_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK   = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK
    };


	enum ShaderType {
		HYD_STAGE_UNSPECIFIED       			 = 0x00000000,
		HYD_STAGE_VERTEX_SHADER     			 = 0x00000001,
		HYD_STAGE_TESSELLATION_CONTROL_SHADER    = 0x00000002,
		HYD_STAGE_TESSELLATION_EVALUATION_SHADER = 0x00000004,
		HYD_STAGE_GEOMETRY_SHADER 				 = 0x00000008,
		HYD_STAGE_FRAGMENT_SHADER 				 = 0x00000010,
        HYD_STAGE_ALL                            = 0x1F
	};


    enum FilterMode
    {
        HYD_FILTER_NEAREST  = VK_FILTER_NEAREST,
        HYD_FILTER_LINEAR   = VK_FILTER_LINEAR,
        HYD_FILTER_MAX_ENUM = VK_FILTER_MAX_ENUM
    };

    enum MipMapFilterMode
    {
        HYD_SAMPLER_MIPMAP_MODE_NEAREST  = VK_SAMPLER_MIPMAP_MODE_NEAREST,
        HYD_SAMPLER_MIPMAP_MODE_LINEAR   = VK_SAMPLER_MIPMAP_MODE_LINEAR,
        HYD_SAMPLER_MIPMAP_MODE_MAX_ENUM = VK_SAMPLER_MIPMAP_MODE_MAX_ENUM
    };

    enum WrapMode
    {
        HYD_SAMPLER_WRAP_MODE_REPEAT               = VK_SAMPLER_ADDRESS_MODE_REPEAT,
        HYD_SAMPLER_WRAP_MODE_MIRRORED_REPEAT      = VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT,
        HYD_SAMPLER_WRAP_MODE_CLAMP_TO_EDGE        = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        HYD_SAMPLER_WRAP_MODE_CLAMP_TO_BORDER      = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,
        HYD_SAMPLER_WRAP_MODE_MIRROR_CLAMP_TO_EDGE = VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE
    };

    enum ColorWriteMask
    {
        HYD_COLOR_COMPONENT_R = VK_COLOR_COMPONENT_R_BIT,
        HYD_COLOR_COMPONENT_G = VK_COLOR_COMPONENT_G_BIT,
        HYD_COLOR_COMPONENT_B = VK_COLOR_COMPONENT_B_BIT,
        HYD_COLOR_COMPONENT_A = VK_COLOR_COMPONENT_A_BIT
    };


    enum ColorBlendFactors
    {
        HYD_BLEND_FACTOR_ZERO                     = VK_BLEND_FACTOR_ZERO,
        HYD_BLEND_FACTOR_ONE                      = VK_BLEND_FACTOR_ONE,
        HYD_BLEND_FACTOR_SRC_COLOR                = VK_BLEND_FACTOR_SRC_COLOR,
        HYD_BLEND_FACTOR_ONE_MINUS_SRC_COLOR      = VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
        HYD_BLEND_FACTOR_DST_COLOR                = VK_BLEND_FACTOR_DST_COLOR,
        HYD_BLEND_FACTOR_ONE_MINUS_DST_COLOR      = VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR,
        HYD_BLEND_FACTOR_SRC_ALPHA                = VK_BLEND_FACTOR_SRC_ALPHA,
        HYD_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA      = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
        HYD_BLEND_FACTOR_DST_ALPHA                = VK_BLEND_FACTOR_DST_ALPHA,
        HYD_BLEND_FACTOR_ONE_MINUS_DST_ALPHA      = VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
        HYD_BLEND_FACTOR_CONSTANT_COLOR           = VK_BLEND_FACTOR_CONSTANT_COLOR,
        HYD_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR,
        HYD_BLEND_FACTOR_CONSTANT_ALPHA           = VK_BLEND_FACTOR_CONSTANT_ALPHA,
        HYD_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA,
        HYD_BLEND_FACTOR_SRC_ALPHA_SATURATE       = VK_BLEND_FACTOR_SRC_ALPHA_SATURATE,
        HYD_BLEND_FACTOR_SRC1_COLOR               = VK_BLEND_FACTOR_SRC1_COLOR,
        HYD_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR     = VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR,
        HYD_BLEND_FACTOR_SRC1_ALPHA               = VK_BLEND_FACTOR_SRC1_ALPHA,
        HYD_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA     = VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA
    };

    enum ColorBlendOp
    {
        HYD_BLEND_OP_ADD              = VK_BLEND_OP_ADD,
        HYD_BLEND_OP_SUBTRACT         = VK_BLEND_OP_SUBTRACT,
        HYD_BLEND_OP_REVERSE_SUBTRACT = VK_BLEND_OP_REVERSE_SUBTRACT,
        HYD_BLEND_OP_MIN              = VK_BLEND_OP_MIN,
        HYD_BLEND_OP_MAX              = VK_BLEND_OP_MAX
    };
};